version: 2
shared: &shared
  working_directory: ~/cereal
  steps:
    - checkout
    - run:
        command: |
          sudo pip install pipenv
          pipenv install --dev
    - run:
        command: |
          pipenv run tox
jobs:
  "python-3.5":
    <<: *shared
    docker:
      - image: circleci/python:3.5.5
  "python-3.6":
    <<: *shared
    docker:
      - image: circleci/python:3.6.4
  "coverage":
    <<: *shared
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          command: |
            sudo pip install pipenv
            pipenv install --dev
      - run:
          command: |
            pipenv run pytest --cov-report html --cov=cereal tests --ds=tests.testapp.settings
      - store_artifacts:
          path: htmlcov
workflows:
  version: 2
  build:
    jobs:
      - "python-3.5"
      - "python-3.6"
      - "coverage"
